import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
	{
		_id: uuid(),
		firstName: "Adarsh",
		lastName: "Balika",
		username: "adarshbalika@gmail.com",
		userHandler: "adarshbalika",
		password: "password",
		bio: "This is a sample bio.",
		link: "https://adarshbalika.netlify.app",
		profilePic: "https://res.cloudinary.com/dgqcspunt/image/upload/v1657672568/HsQgVOfP_400x400_kzq2un.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		_id: uuid(),
		firstName: "Chaitanya",
		lastName: "Chhikara",
		username: "chaitanya@gmail.com",
		userHandler: "chaitanya",
		password: "password",
		bio: "Learning web dev right now.",
		link: "https://bruh.dev",
		profilePic: "https://res.cloudinary.com/dgqcspunt/image/upload/v1657670519/chaitanya-dp_qsglf1.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		_id: uuid(),
		firstName: "Guest",
		lastName: "One",
		username: "guest1@gmail.com",
		userHandler: "guest1",
		password: "guest1",
		bio: "This is Guest One Bio",
		link: "https://example.com",
		profilePic: "https://res.cloudinary.com/dgqcspunt/image/upload/v1657672772/MpQnHp1P_400x400_quhuxb.png",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		_id: uuid(),
		firstName: "Guest",
		lastName: "Two",
		username: "guest2@gmail.com",
		userHandler: "guest2",
		password: "guest2",
		bio: "This is Guest Two Bio",
		link: "https://example.com",
		profilePic: "https://res.cloudinary.com/dgqcspunt/image/upload/v1657672777/T-5_3R7f_400x400_qq1vyf.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		_id: uuid(),
		firstName: "Guest",
		lastName: "Three",
		username: "guest3@gmail.com",
		userHandler: "guest3",
		password: "guest3",
		bio: "This is Guest Three Bio",
		link: "https://example.com",
		profilePic: "https://res.cloudinary.com/dgqcspunt/image/upload/v1657672782/Nyn1HZWF_400x400_p297er.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		_id: uuid(),
		firstName: "Guest",
		lastName: "Four",
		username: "guest4@gmail.com",
		userHandler: "guest4",
		password: "guest4",
		bio: "This is Guest Four Bio",
		link: "https://example.com",
		profilePic: "https://res.cloudinary.com/dgqcspunt/image/upload/v1657672786/wiCurSFZ_400x400_ql0ft5.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		_id: uuid(),
		firstName: "Guest",
		lastName: "Five",
		username: "guest5@gmail.com",
		userHandler: "guest5",
		password: "guest5",
		bio: "This is Guest Five Bio",
		link: "https://example.com",
		profilePic: "https://res.cloudinary.com/dgqcspunt/image/upload/v1657672795/GS3tLkLD_400x400_wot8hm.png",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
];
